'''
ORIGINAL URL
INCEPTION_CKPT_URL = 'https://deepbase-1251068397.cos.ap-guangzhou.myqcloud.com/inception_v3.ckpt'
VGG_NPY_URL = 'https://deepbase-1251068397.cos.ap-guangzhou.myqcloud.com/vgg19.npy'
LAPSRN_URL = 'https://deepbase-1251068397.cos.ap-guangzhou.myqcloud.com/lapsrn.npz'
YOLO_TINY_CKPT_URL = 'https://deepbase-1251068397.cos.ap-guangzhou.myqcloud.com/yolo_tiny.ckpt'
'''
INCEPTION_CKPT_URL = 'http://cdn.zhitantech.com/static/inception_v3.ckpt'
VGG_NPY_URL = 'http://cdn.zhitantech.com/static/vgg19.npy'
LAPSRN_URL = 'http://cdn.zhitantech.com/static/lapsrn.npz'
YOLO_TINY_CKPT_URL = 'http://cdn.zhitantech.com/static/yolo_tiny.ckpt'
